### PR TITLE
Proxy /ident for helper mode

### PR DESCRIPTION
**Pull request by justincy**
Tested locally in storybook

### CODE REVIEW

**Comment by redbugz** [comment]
What endoint does helper use on `/ident`. I would like to be aware so we can consider other options in the future.

**Comment by justincy** [comment]
Can you do a new release? No one will be able to test the helper component I'm working on without this.

**Comment by joeycozza** [comment]
Working on it. Trying to iron out some build issues.
There is a big red X on https://github.com/fs-webdev/create-react-app/pull/102

**Comment by joeycozza** [comment]
finally figured it out. react-scripts 2.0.0 was released.

**Pull request merged**
