### PR TITLE
upgrade to zion 4 alpha

### PR DESCRIPTION
**Pull request by jsbalrog**

### CODE REVIEW

**Comment by joeycozza** [comment]
So there were no necessary changes to bump us up? That's cool.

**Comment by jsbalrog** [comment]
Yeah, @joeycozza I tested stuff, and everything worked okay.

**Comment by redbugz** [comment]
don't we need to change the version to a pre-release as well?

**Comment by jsbalrog** [comment]
@redbugz do you mean something different than 4.0.0-alpha.1?

**Comment by redbugz** [comment]
no, the RC version. Are we going to release an RC pointing to the alpha. I'm guessing for testing before they release the final later today?

**Comment by jsbalrog** [comment]
@joeycozza Do we need to bump the RC version to 18 as well?

**Comment by joeycozza** [comment]
PR's going into the develop branch should just be the PR.

Once the develop branch is ready to cut a release, we bump the version on the develop branch, and merge that into frontierMaster. 

So for this PR, no need to bump the version.

**Comment by joeycozza** [comment]
I say we wait until they make an actual v4 release (probably happening today).

Then we tweak this to be `zion-ui@4`. (and do another quick test to make sure nothing else broke.

**Comment by jsbalrog** [comment]
Sounds good. Currently in the Zion meeting; probably happening Monday... I'll make it so next week.

**Comment by joeycozza** [comment]
yeah, I guess that wouldn't hurt. go ahead and close this PR

**Pull request closed without merging**
